name: SDET Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Correr tests en Docker
        run: docker compose up --build --abort-on-container-exit

      - name: Generar reporte Allure
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: target/allure-results
          allure_report: allure-report

      - name: Configurar credenciales AWS
        if: always()
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Subir reporte a S3
        if: always()
        run: aws s3 sync allure-report s3://sdet-reportes-allure-8754/reportes/${{ github.run_number }}/